#!/usr/bin/env python3
"""Generate supplemental connectivity table with 95% Wilson CIs.

Reads nb_connectivity_metrics.csv from the adhesion decoupling sweep and
produces a long-form CSV and a LaTeX table fragment showing, for each
(regulatory_dynamic × adhesion × relrot_label) cell, the fraction of runs
with all NBs connected and the 95% Wilson confidence interval.

Usage:
    uv run python scripts/generate_connectivity_ci_table.py \
        --proc-dir data/sim/processed_decoupling_adhesion \
        --out-dir  docs/tex_draft/figures
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import pandas as pd

REG_DYN_ORDER = ["VOL-ABM", "VOL-PDE"]
ADH_ORDER = [50, 40, 20]
RELROT_ORDER = ["off", "mu=0", "mu=45", "mu=90"]
RELROT_TEX = {"off": "off", "mu=0": r"$\mu$=0°", "mu=45": r"$\mu$=45°", "mu=90": r"$\mu$=90°"}

Z95 = 1.96


def wilson_ci(k: int, n: int) -> tuple[float, float, float]:
    """Return (frac, ci_lo, ci_hi) using the Wilson score interval at 95%."""
    if n == 0:
        return math.nan, math.nan, math.nan
    p = k / n
    z2 = Z95 ** 2
    denom = 1 + z2 / n
    center = (p + z2 / (2 * n)) / denom
    margin = Z95 * math.sqrt(p * (1 - p) / n + z2 / (4 * n ** 2)) / denom
    return round(p, 4), round(max(0.0, center - margin), 4), round(min(1.0, center + margin), 4)


def _relrot_label(row: pd.Series) -> str:
    if not row["relrot"]:
        return "off"
    m = row["relrot_mean"]
    return f"mu={int(m)}" if not pd.isna(m) else "mu=?"


def load_connectivity(proc_dir: Path) -> pd.DataFrame:
    df = pd.read_csv(proc_dir / "nb_connectivity_metrics.csv")
    df["adhesion"] = df["adhesion"].astype(int)
    df["relrot_label"] = df.apply(_relrot_label, axis=1)
    return df


def build_long_table(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for reg_dyn in REG_DYN_ORDER:
        for adh in ADH_ORDER:
            for rl in RELROT_ORDER:
                sub = df[
                    (df["regulatory_dynamic"] == reg_dyn)
                    & (df["adhesion"] == adh)
                    & (df["relrot_label"] == rl)
                ]["nb_connected"]
                n_total = len(sub)
                n_conn = int(sub.sum()) if n_total > 0 else 0
                frac, ci_lo, ci_hi = wilson_ci(n_conn, n_total)
                rows.append({
                    "regulatory_dynamic": reg_dyn,
                    "adhesion": adh,
                    "relrot_label": rl,
                    "n_connected": n_conn,
                    "n_total": n_total,
                    "frac": frac,
                    "ci_lo": ci_lo,
                    "ci_hi": ci_hi,
                })
    return pd.DataFrame(rows)


def _cell_str(row: pd.Series) -> str:
    if math.isnan(row["frac"]):
        return "--"
    return f"{row['frac']:.2f} [{row['ci_lo']:.2f}, {row['ci_hi']:.2f}]"


def build_latex(long_df: pd.DataFrame) -> str:
    col_headers = " & ".join(["Adhesion"] + [RELROT_TEX[r] for r in RELROT_ORDER])
    lines = [
        r"\% Auto-generated by scripts/generate_connectivity_ci_table.py",
        r"\% Each cell: fraction connected [95\% Wilson CI], n=50 runs per condition.",
        "",
    ]

    for reg_dyn in REG_DYN_ORDER:
        lines += [
            r"\begin{table}[h]",
            r"\centering",
            rf"\caption{{{reg_dyn}: fraction of runs with all NBs connected (95\% Wilson CI)}}",
            r"\begin{tabular}{l" + "c" * len(RELROT_ORDER) + "}",
            r"\toprule",
            col_headers + r" \\",
            r"\midrule",
        ]
        sub = long_df[long_df["regulatory_dynamic"] == reg_dyn]
        for adh in ADH_ORDER:
            adh_rows = sub[sub["adhesion"] == adh]
            cells = []
            for rl in RELROT_ORDER:
                match = adh_rows[adh_rows["relrot_label"] == rl]
                if match.empty:
                    cells.append("--")
                else:
                    cells.append(_cell_str(match.iloc[0]))
            lines.append(f"J={adh} & " + " & ".join(cells) + r" \\")
        lines += [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ]

    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--proc-dir", type=Path,
                   default=Path("data/sim/processed_decoupling_adhesion"))
    p.add_argument("--out-dir", type=Path,
                   default=Path("docs/tex_draft/figures"))
    return p.parse_args()


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    df = load_connectivity(args.proc_dir)
    long_df = build_long_table(df)

    csv_path = args.out_dir / "figure5_supp_connectivity_ci_table.csv"
    long_df.to_csv(csv_path, index=False)
    print(f"wrote {csv_path} ({len(long_df)} rows)")

    tex_path = args.out_dir / "figure5_supp_connectivity_ci_table.tex"
    tex_path.write_text(build_latex(long_df), encoding="utf-8")
    print(f"wrote {tex_path}")


if __name__ == "__main__":
    main()
